INSERT INTO estado (sg_estado,ds_nome) VALUES ('AC','ACRE');
INSERT INTO estado (sg_estado,ds_nome) VALUES ('AL','ALAGOAS');
INSERT INTO estado (sg_estado,ds_nome) VALUES ('AP','AMAPÁ');
INSERT INTO estado (sg_estado,ds_nome) VALUES ('AM','AMAZONAS');
INSERT INTO estado (sg_estado,ds_nome) VALUES ('BA','BAHIA');
INSERT INTO estado (sg_estado,ds_nome) VALUES ('CE','CEARÁ');
INSERT INTO estado (sg_estado,ds_nome) VALUES ('DF','DISTRITO FEDERAL');
INSERT INTO estado (sg_estado,ds_nome) VALUES ('ES','ESPÍRITO SANTO');
INSERT INTO estado (sg_estado,ds_nome) VALUES ('GO','GOIÁS');
INSERT INTO estado (sg_estado,ds_nome) VALUES ('MA','MARANHÃO');
INSERT INTO estado (sg_estado,ds_nome) VALUES ('MT','MATO GROSSO');
INSERT INTO estado (sg_estado,ds_nome) VALUES ('MS','MATO GROSSO DO SUL');
INSERT INTO estado (sg_estado,ds_nome) VALUES ('MG','MINAS GERAIS');
INSERT INTO estado (sg_estado,ds_nome) VALUES ('PA','PARÁ');
INSERT INTO estado (sg_estado,ds_nome) VALUES ('PB','PARAÍBA');
INSERT INTO estado (sg_estado,ds_nome) VALUES ('PR','PARANÁ');
INSERT INTO estado (sg_estado,ds_nome) VALUES ('PE','PERNAMBUCO');
INSERT INTO estado (sg_estado,ds_nome) VALUES ('PI','PIAUÍ');
INSERT INTO estado (sg_estado,ds_nome) VALUES ('RJ','RIO DE JANEIRO');
INSERT INTO estado (sg_estado,ds_nome) VALUES ('RN','RIO GRANDE DO NORTE');
INSERT INTO estado (sg_estado,ds_nome) VALUES ('RS','RIO GRANDE DO SUL');
INSERT INTO estado (sg_estado,ds_nome) VALUES ('RO','RONDÔNIA');
INSERT INTO estado (sg_estado,ds_nome) VALUES ('RR','RORAIMA');
INSERT INTO estado (sg_estado,ds_nome) VALUES ('SC','SANTA CATARINA');
INSERT INTO estado (sg_estado,ds_nome) VALUES ('SE','SERGIPE');
INSERT INTO estado (sg_estado,ds_nome) VALUES ('SP','SÃO PAULO');
INSERT INTO estado (sg_estado,ds_nome) VALUES ('TO','TOCANTINS');